const data = [
  { name: "Hummus", price: "$5.00", id: "1A" },
  { name: "Moutabal", price: "$5.00", id: "2B" },
  { name: "Falafel", price: "$7.50", id: "3C" },
  { name: "Marinated Olives", price: "$5.00", id: "4D" },
  { name: "Kofta", price: "$5.00", id: "5E" },
  { name: "Eggplant Salad", price: "$8.50", id: "6F" },
  { name: "Lentil Burger", price: "$10.00", id: "7G" },
  { name: "Smoked Salmon", price: "$14.00", id: "8H" },
  { name: "Kofta Burger", price: "$11.00", id: "9I" },
  { name: "Turkish Kebab", price: "$15.50", id: "10J" },
  { name: "Fries", price: "$3.00", id: "11K" },
  { name: "Buttered Rice", price: "$3.00", id: "12L" },
  { name: "Bread Sticks", price: "$3.00", id: "13M" },
  { name: "Pita Pocket", price: "$3.00", id: "14N" },
  { name: "Lentil Soup", price: "$3.75", id: "15O" },
  { name: "Greek Salad", price: "$6.00", id: "16Q" },
  { name: "Rice Pilaf", price: "$4.00", id: "17R" },
  { name: "Baklava", price: "$3.00", id: "18S" },
  { name: "Tartufo", price: "$3.00", id: "19T" },
  { name: "Tiramisu", price: "$5.00", id: "20U" },
  { name: "Panna Cotta", price: "$5.00", id: "21V" },
];

export default fakeData = [
  {
    pillName: "abc",
    imageURI: "./assets/icons/add_medicine.png",
    id: "1A",
    quantity: "1",
    dose: "1",
    note: "Before Meals",
    time: "2.56",
  },
  {
    pillName: "azd",
    imageURI: "./assets/icons/add_medicine.png",
    id: "6A",
    quantity: "1",
    dose: "1",
    note: "Every Other Day",
    time: "2.56",
  },
];

export const medicineTimeData = [
  {
    key: "1",
    id: "1",
    medicineName: "abcd",
    medicineImage: "",
    priority: "LOW",
    pill: [
      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "1A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },

      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "2A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },

      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "3A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },

      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "4A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },
    ],
  },
  {
    key: "2",
    id: "10",
    medicineName: "abcd",
    medicineImage: "",
    priority: "LOW",
    pill: [
      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "5A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },

      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "6A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },
    ],
  },
  {
    key: "3",
    id: "9",
    medicineName: "abcd",
    medicineImage: "",
    priority: "LOW",
    pill: [
      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "5A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },

      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "6A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },
    ],
  },
  {
    key: "4",
    id: "8",
    medicineName: "abcd",
    medicineImage: "",
    priority: "LOW",
    pill: [
      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "5A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },

      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "6A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },
    ],
  },
  {
    key: "5",
    id: "7",
    medicineName: "abcd",
    medicineImage: "",
    priority: "LOW",
    pill: [
      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "5A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },

      {
        pillName: "abc",
        imageURI: "./assets/icons/add_medicine.png",
        id: "6A",
        quantity: "1",
        dose: "1",
        note: "Before Meals",
        time: "2.56",
      },
    ],
  },
];
